---
galaxy_info:
  role_name: dr_failback_prepare_forward_amr
  namespace: netapp
  author: Kamini Singh
  description: Prepare the system to re-establish forward replication from the original primary to the destination cluster as part of the failback workflow.
  company: NetApp
  license: Apache-2.0
  min_ansible_version: "2.16"
  galaxy_tags:
    - netapp
    - trident
    - tridentprotect
    - appmirrorrelationship
    - dataprotection
    - failback
    - openshift
    - kubernetes
    - storage
    - disasterrecovery

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
